name: .NET
on: [push, pull_request]

jobs:
  job:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Restore
        run: dotnet restore IMPA
      - name: Build
        run: dotnet build --configuration Release --no-restore IMPA
      - name: Test
        run: dotnet test IMPA.Tests
